CREATE LOGIN ADMINISTRATOR
	WITH PASSWORD = 'adminPassword'
CREATE USER ADMINISTRATOR FOR LOGIN ADMINISTRATOR;

CREATE LOGIN LIBRARIAN
	WITH PASSWORD = 'librarianPassword'
CREATE USER LIBRARIAN FOR LOGIN LIBRARIAN;

CREATE LOGIN MEMBER
	WITH PASSWORD = 'memberPassword'
CREATE USER MEMBER FOR LOGIN MEMBER;