begin tran privileges

grant SELECT, UPDATE, DELETE, INSERT ON Address to ADMINISTRATOR WITH GRANT OPTION
grant SELECT, UPDATE, DELETE, INSERT ON Author to ADMINISTRATOR WITH GRANT OPTION
grant SELECT, UPDATE, DELETE, INSERT ON Book to ADMINISTRATOR WITH GRANT OPTION
grant SELECT, UPDATE, DELETE, INSERT ON BookAuthor to ADMINISTRATOR WITH GRANT OPTION
grant SELECT, UPDATE, DELETE, INSERT ON Library to ADMINISTRATOR WITH GRANT OPTION
grant SELECT, UPDATE, DELETE, INSERT ON Loan to ADMINISTRATOR WITH GRANT OPTION
grant SELECT, UPDATE, DELETE, INSERT ON Member to ADMINISTRATOR WITH GRANT OPTION
grant SELECT, UPDATE, DELETE, INSERT ON Volume to ADMINISTRATOR WITH GRANT OPTION

deny ALTER ON Address to ADMINISTRATOR
deny ALTER ON Author to ADMINISTRATOR
deny ALTER ON Book to ADMINISTRATOR
deny ALTER ON BookAuthor to ADMINISTRATOR
deny ALTER ON Library to ADMINISTRATOR
deny ALTER ON Loan to ADMINISTRATOR
deny ALTER ON Member to ADMINISTRATOR
deny ALTER ON Volume to ADMINISTRATOR

grant SELECT, UPDATE, INSERT ON Address to LIBRARIAN
grant SELECT, UPDATE, INSERT ON Author to LIBRARIAN
grant SELECT, UPDATE, INSERT ON Book to LIBRARIAN
grant SELECT, UPDATE, INSERT ON BookAuthor to LIBRARIAN
grant SELECT, UPDATE, INSERT ON Library to LIBRARIAN
grant SELECT, UPDATE, INSERT ON Loan to LIBRARIAN
grant SELECT, UPDATE, INSERT ON Member to LIBRARIAN
grant SELECT, UPDATE, INSERT ON Volume to LIBRARIAN

deny DELETE, ALTER ON Address to MEMBER
deny DELETE, ALTER ON Author to MEMBER
deny DELETE, ALTER ON Book to MEMBER
deny DELETE, ALTER ON BookAuthor to MEMBER
deny DELETE, ALTER ON Library to MEMBER
deny DELETE, ALTER ON Loan to MEMBER
deny DELETE, ALTER ON Member to MEMBER
deny DELETE, ALTER ON Volume to MEMBER

grant SELECT ON Address to MEMBER
grant SELECT ON Author to MEMBER
grant SELECT ON Book to MEMBER
grant SELECT ON BookAuthor to MEMBER
grant SELECT ON Library to MEMBER
grant SELECT ON Loan to MEMBER
grant SELECT ON Member to MEMBER
grant SELECT ON Volume to MEMBER

deny UPDATE, INSERT, DELETE, ALTER ON Address to MEMBER
deny UPDATE, INSERT, DELETE, ALTER ON Author to MEMBER
deny UPDATE, INSERT, DELETE, ALTER ON Book to MEMBER
deny UPDATE, INSERT, DELETE, ALTER ON BookAuthor to MEMBER
deny UPDATE, INSERT, DELETE, ALTER ON Library to MEMBER
deny UPDATE, INSERT, DELETE, ALTER ON Loan to MEMBER
deny UPDATE, INSERT, DELETE, ALTER ON Member to MEMBER
deny UPDATE, INSERT, DELETE, ALTER ON Volume to MEMBER

commit tran privileges