BEGIN TRAN drop_tables;

DROP TABLE IF EXISTS Loan;
DROP TABLE IF EXISTS BookAuthor;
DROP TABLE IF EXISTS Volume;
DROP TABLE IF EXISTS Library;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Address;

COMMIT TRAN drop_tables;